version: '3'
services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=inventory-app
    ports:
      - 27017:27017
    volumes:
      - /Users/markusjohansson/dev/docker-volumes/inventory

  # TODO: Add spring app