version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  spring-backend:
    build:
      context: ./backend
    container_name: spring-backend
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - DB_HOST=app_db
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb:app_db
#
  react-frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    environment:
      - PROXY=http://backend:8080
    ports:
      - "3000:3000"
    links:
      - spring-backend:backend